[theme]
primaryColor = "#0082C3"
backgroundColor = "#EFF8FD"
secondaryBackgroundColor = "#EAF7FF"
textColor = "#12324A"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
